### PR TITLE
Cumulative

### PR DESCRIPTION
**Pull request by tobyhinloopen**
Don't you hate merge conflicts? I do.

https://github.com/fabiooshiro/xlsx-calc/pull/37
https://github.com/fabiooshiro/xlsx-calc/pull/36
https://github.com/fabiooshiro/xlsx-calc/pull/35

In one PR

### CODE REVIEW

**Comment by fabiooshiro** [comment]
do you have an advice?

**Comment by tobyhinloopen** [comment]
@fabiooshiro advice regarding what, exactly?

**Comment by fabiooshiro** [comment]
how to avoid it...
the bundle is conflicting .map and .min

Em sex, 5 de jul de 2019 11:10, Toby Hinloopen <notifications@github.com>
escreveu:

**Comment by tobyhinloopen** [comment]
.map & .min always conflict since these aren't source files. These are minified and git doesn't changes  in minified files.

I usually just drop them & recreate them - for source control, you only care about changes in the source. Ideally you don't have the minified version in source control at all. You use release builds for that, or allow the user to build it. IIRC how-to-build isn't documented either.

**Comment by tobyhinloopen** [comment]
Note that the minified versions in the root of the repo haven't been updated.

**Comment by fabiooshiro** [comment]
Hummm, the point is the way we are doing the tests...
transpiling and running tests against that min version

**Comment by tobyhinloopen** [comment]
I don't think you're running tests against the minified version, or the tests would have failed.

**Pull request merged**
